version: "3.5"

services:
  front:
    build:
      context: ./palletmaster
      dockerfile: Dockerfile
    volumes:
      - ./palletmaster:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
      # docker-compose run front /bin/sh
      # docker-compose run --rm front yarn start
      # 0.0.0.0:3000で繋がる
